#!/bin/bash
person1="Ramesh"
person2="Suresh"
echo "$person1:: Hi $person2, How are you?"
echo "$person2:: Hi $person1, I am fine. How about you?"
echo "$person1:: I am also good. What are you doing these days?"
echo "$person2:: I am learning shell scripting."        
